config/routes.rb
Rails.application.routes.draw do
  

  resources :memberships do
    post 'toggle_confirmed', on: :member
  end  
  resources :beer_clubs
  resources :users do
    post 'toggle_banned', on: :member
  end   
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :styles
  root 'breweries#index'
  get 'beerlist', to:'beers#list'
  get 'auth/:provider/callback', to: 'sessions#create_oauth'
  get 'brewerylist', to:'breweries#list'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :places, only:[:index, :show]
  post 'places', to:'places#search'

  resource :session, only: [:new, :create, :destroy]
  resources :ratings, only: [:index, :new, :create, :destroy]

end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
	include AverageRating

	validates :name, presence: true, allow_blank: false
	validates :year, numericality: { greater_than_or_equal_to: 1042,
									   less_than_or_equal_to: ->(_brewery){Date.current.year},
                                       only_integer: true } 


	scope :active, -> {where active:true}
	scope :retired, -> {where active:[nil,false]}								   

	has_many :beers, dependent: :destroy
	has_many :ratings, through: :beers

	def print_report
    	puts name
    	puts "established at year #{year}"
    	puts "number of beers #{beers.count}"
  	end

	def restart
		self.year = 2017
		puts "changed year to #{year}"
	end

	def to_s 
	  self.name	
	end	

	def self.top(size)	
	  sorted_by_rating = Brewery.all.sort_by{|b| b.average_rating}
	  sorted_by_rating.reverse.first(size)  

	end
	

		  

end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show, :list]
  before_action :skip_if_cached, only:[:index]

  def skip_if_cached
    @order = params[:order] || 'name'
    return render :index if request.format.html? and fragment_exist?( "beerlist-#{@order}" )
  end
  


  # GET /breweries
  # GET /breweries.json
  def index
    @breweries = Brewery.all
    

    order = params[:order] || 'name'
    



    @breweries = case order
      when 'name' then 
        if params[:order]  == session[:last_order] && session[:is_reversed] == false
          session[:is_reversed] = true
          @breweries.sort_by{ |b| b.name}.reverse
        else 
          session[:is_reversed] = false
          @breweries.sort_by{ |b| b.name}
        end
     when 'year' then 
        if params[:order]  == session[:last_order]  && session[:is_reversed] == false
          session[:is_reversed] = true
          @breweries.sort_by{ |b| b.year}.reverse
        else 
          session[:is_reversed] = false
          @breweries.sort_by{ |b| b.year}
        end     
     end

   

    session[:last_order] = order
    
  end

  def list
  end  

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    ["brewerylist-name", "brewerylist-brewery", "brewerylist-style"].each{ |f| expire_fragment(f) }
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    ["brewerylist-name", "brewerylist-brewery", "brewerylist-style"].each{ |f| expire_fragment(f) }
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end


  def toggle_activity
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, (not brewery.active)

    new_status = brewery.active? ? "active" : "retired"

    redirect_to :back, notice:"brewery activity status chnged to #{new_status}"
 end   
  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    ["brewerylist-name", "brewerylist-brewery", "brewerylist-style"].each{ |f| expire_fragment(f) }
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:name, :year, :active)
    end


  private

    


end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= bootstrap_form_for(@brewery) do |f| %>
<div class="form-group">
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :active%>
    <%= f.check_box :active%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>  
<% end %>

app/views/breweries/_list.html.erb
<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th><%= link_to 'Name', breweries_path(order:"name") %></th>
        <th><%= link_to 'Year', breweries_path(order:"year") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/breweries/edit.html.erb
<h1>Editing Brewery</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<p id="notice"><%= notice %></p>


<% cache "brewerylist#{@order}", skip_digest: true do %>

<div class="row">

  <div class="col-sm-6">
    <h1>Listing breweries</h1>
    <p> Number of active breweries: <%= @breweries.count %> </p>

    <%= render 'list', breweries: @breweries %>
  </div>
  
<% end %>

<br>

<%= link_to('New Brewery', new_brewery_path) if current_user%>

app/views/breweries/list.html.erb
<h2>Breweries</h2>

<table id="brewerytable" class="table table-hover">
  <tr>
    <th> <a href="#" id="name">Name</a> </th>
    <th> <a href="#" id="year">Established</a> </th>
    <th> <a href="#" id="beerCount">No. of beers</a> </th>
  </tr>

</table>

app/views/breweries/new.html.erb
<h1 class="new_brewery">New Brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/show.html.erb
<p id="notice"><%= notice %></p>

<% cache @beer do %>

<h2>
  <%= @brewery.name %>
  <% if not @brewery.active %>
    <span class="label label-info">retired</span>
  <% end %>	
</h2>
<% if current_user && current_user.admin? %>
    <%= link_to 'Destroy', @brewery, method: :delete, class:"btn btn-danger", data: { confirm: 'Are you sure?' } %>  
    <%= link_to "change activity", toggle_activity_brewery_path(@brewery.id), method: :post, class: "btn btn-primary" %>
<% end %>

<p>
  <i>Established in 
  <%= @brewery.year %> </i>
</p>

<p>Number of beers: <%= @brewery.beers.count %></p>




<ul class="list-group">
	<% @brewery.beers.each do |beer| %>
		<li class="list-group-item"><%= beer.name %></li>
	<% end %>
</ul>	


<% if @brewery.ratings.empty? %>
	<p>Beers from this brewery has not yet been rated</p>
<% else %>
    <p> Has <%= pluralize(@brewery.ratings.count, 'rating')%>, average <%= @brewery.average_rating %></p>
<% end %>		

<% end %>
<%= edit_and_destroy_buttons(@brewery) %>