config/routes.rb
Rails.application.routes.draw do
  

  resources :memberships do
    post 'toggle_confirmed', on: :member
  end  
  resources :beer_clubs
  resources :users do
    post 'toggle_banned', on: :member
  end   
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :styles
  root 'breweries#index'
  get 'beerlist', to:'beers#list'
  get 'auth/:provider/callback', to: 'sessions#create_oauth'
  get 'brewerylist', to:'breweries#list'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :places, only:[:index, :show]
  post 'places', to:'places#search'

  resource :session, only: [:new, :create, :destroy]
  resources :ratings, only: [:index, :new, :create, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ratebeer</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

  <div class="navbar navbar-inverse">
    <main role"main" class=".container">
    <ul class="nav navbar-nav">
      <li><%= link_to 'breweries', breweries_path %></li>
      <li><%= link_to 'beers', beers_path %></li>
      <li><%= link_to 'ratings', ratings_path %></li>
      <li><%= link_to 'beer clubs', beer_clubs_path%></li>
      <li><%= link_to 'users', users_path%></li>
      <li><%= link_to 'places', places_path%></li>
      <li><%= link_to 'styles', styles_path %></li>
  
  
      <% if current_user %>
      
       
              <li><%= link_to 'your profile', current_user%></li>
              <li><%= link_to 'rate a beer', new_rating_path %></li>
              <li><%= link_to 'join a club', new_membership_path%></li>
              <li><%= link_to 'sign out', '/signout', method: :delete%></li>
           
    
      <% else %>
        <li><%= link_to 'sign in', '/signin'%></li>
        <li><%= link_to 'sign up', '/signup'%></li>
      <% end %>  
        </ul>
      </div>

      <div id="infobox">
        <% if current_user %>
          <p><%= current_user.username %> signed in</p>
        <% end %>

        <% if session[:last_rating].nil? %>
          <p>no ratings given</p>
        <% else %>
          <p>previous rating <%= session[:last_rating] %></p>
        <% end %>
      </div>

      <div id="base" class="row">
        <div class="col-md-8">
          <%= yield %>
        </div> 
      </div>

    </main>
  </body>
</html>